/**
 * Writes src/generated/iso4217.ts from the ISO 4217 list maintained by SIX. Run with `npm run generate:currencies` when the
 * list changes, and commit what it writes.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SOURCE = 'https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml';
const SYMBOLS: Record<string, string> = { USD: '$', EUR: '€', GBP: '£', JPY: '¥', INR: '₹', CAD: 'CA$', BHD: 'BD', KWD: 'KD', CLF: 'UF' };
const WANTED = ['BHD', 'CAD', 'CHF', 'CLF', 'EUR', 'GBP', 'INR', 'JPY', 'KWD', 'USD'];

interface Entry { code: string; digits: number; name: string }

export function readList(xml: string): Entry[] {
  const entries: Entry[] = [];
  for (const block of xml.split('<CcyNtry>').slice(1)) {
    const code = /<Ccy>([A-Z]{3})<\/Ccy>/.exec(block)?.[1];
    const digits = /<CcyMnrUnts>(\d+)<\/CcyMnrUnts>/.exec(block)?.[1];
    const name = /<CcyNm[^>]*>([^<]+)<\/CcyNm>/.exec(block)?.[1];
    if (code && digits && name && !entries.some(entry => entry.code === code)) entries.push({ code, digits: Number(digits), name });
  }
  return entries.sort((a, b) => a.code.localeCompare(b.code));
}

async function main(): Promise<void> {
  const xml = await (await fetch(SOURCE)).text();
  const rows = readList(xml).filter(entry => WANTED.includes(entry.code))
    .map(entry => `  { code: '${entry.code}', digits: ${entry.digits}, symbol: '${SYMBOLS[entry.code] ?? entry.code}', name: '${entry.name}' },`);
  const out = [
    '// Generated by scripts/generate-currencies.ts from the ISO 4217 list. Do not edit by hand.',
    "import type { CurrencyData } from '../types';",
    '',
    'export const ISO_4217: readonly CurrencyData[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
  writeFileSync(join(__dirname, '..', 'src', 'generated', 'iso4217.ts'), out);
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
