/**
 * C#, run by perch with mutant schemata: every mutant written into the projects once behind a switch, the solution built once,
 * and each mutant run by `dotnet test` over the built test assemblies with PERCH_MUTANT set. A mutant the compiler rejects, a
 * value a constant or an attribute needs at compile time, is taken out and the solution built again; it is invalid, as
 * Stryker.NET counts a compile error.
 *
 * Which test reaches which mutant is recorded by the switches: during the suite run, a switch looks up its call stack for the
 * method marked as a test by xUnit, NUnit or MSTest, through the state machine an async test runs in.
 */
import { execFile } from 'node:child_process';
import { readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { promisify } from 'node:util';
import { mutantId } from '../mutants.js';
import { startDriver } from './driver.js';
import { instrument } from './schemata.js';

const run = promisify(execFile);

export const name = 'dotnet';
export const languages = new Set(['csharp', 'c_sharp']);
/** One copy: mutants are switched on at run time and never written again. */
export const copiesFor = () => 1;

/** The switch each project with mutants gets, as a class of its own outside any namespace. */
const SWITCH = `// <auto-generated/>
#nullable disable
internal static class PerchSwitch
{
    static readonly int Active = int.TryParse(System.Environment.GetEnvironmentVariable("PERCH_MUTANT"), out var value) ? value : -1;
    static readonly string Hits = System.Environment.GetEnvironmentVariable("PERCH_HITS");
    static readonly System.Collections.Concurrent.ConcurrentDictionary<string, bool> Seen = new System.Collections.Concurrent.ConcurrentDictionary<string, bool>();
    static readonly string[] Markers = { "FactAttribute", "TheoryAttribute", "TestAttribute", "TestCaseAttribute", "TestCaseSourceAttribute", "TestMethodAttribute", "DataTestMethodAttribute" };

    internal static bool On(int id)
    {
        if (Hits != null)
        {
            var test = CurrentTest();
            if (Seen.TryAdd(test + "\\t" + id, true)) lock (Seen) System.IO.File.AppendAllText(Hits, id + "\\t" + test + "\\n");
        }
        return Active == id;
    }

    static bool Marked(System.Reflection.MethodBase method)
    {
        foreach (var attribute in method.GetCustomAttributes(false)) if (System.Array.IndexOf(Markers, attribute.GetType().Name) >= 0) return true;
        return false;
    }

    static string CurrentTest()
    {
        foreach (var frame in new System.Diagnostics.StackTrace(false).GetFrames() ?? new System.Diagnostics.StackFrame[0])
        {
            var method = frame.GetMethod();
            var type = method?.DeclaringType;
            if (method == null || type == null) continue;
            if (Marked(method)) return type.FullName + "." + method.Name;
            // An async test runs in a state machine, <Name>d__3, nested in the class that declares it.
            if (method.Name == "MoveNext" && type.Name.StartsWith("<") && type.DeclaringType != null)
            {
                var name = type.Name.Substring(1, type.Name.IndexOf('>') - 1);
                foreach (var candidate in type.DeclaringType.GetMethods(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic))
                {
                    if (candidate.Name == name && Marked(candidate)) return type.DeclaringType.FullName + "." + name;
                }
            }
        }
        return "";
    }
}
`;

let ids = new Map(), keys = new Map(), unplaced = new Map(), assemblies = [], names = new Map(), testOfNode = new Map();

/** A TRX file's results: each test case's name, as VSTest gives it, whether it passed, and how long it took. */
function readTrx(text) {
  const results = [];
  for (const match of text.matchAll(/<UnitTestResult\b([^>]*)>?/g)) {
    const attribute = key => new RegExp(`\\b${key}="([^"]*)"`).exec(match[1])?.[1];
    const outcome = attribute('outcome');
    if (outcome !== 'Passed' && outcome !== 'Failed') continue;
    const duration = attribute('duration')?.split(':').reduce((sum, part) => sum * 60 + Number(part), 0) ?? 0;
    const decode = value => value.replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
    results.push({ name: decode(attribute('testName') ?? ''), status: outcome === 'Passed' ? 'passed' : 'failed', time: duration });
  }
  return results;
}

/** A test case's name without the arguments a theory or a test case gives it: the method it runs. */
const methodOf = testName => testName.replace(/\(.*\)$/s, '');
/** The perch test a VSTest name is: its class and method, which perch names it by. */
const testIdOf = testName => {
  const parts = methodOf(testName).split('.');
  return names.get(parts.slice(-2).join('.')) ?? `dotnet::${methodOf(testName)}`;
};

export async function available({ root }) {
  try { await run('dotnet', ['--version'], { cwd: root }); } catch { return { reason: 'dotnet is not on PATH' }; }
  return { root };
}

/** Every project file under the copy, outside bin and obj. */
async function projects(dir) {
  const { stdout } = await run('find', [dir, '-name', '*.csproj', '-not', '-path', '*/bin/*', '-not', '-path', '*/obj/*'], { maxBuffer: 1 << 24 });
  return stdout.split('\n').filter(Boolean);
}

/** Errors a build printed, `path(line,col): error CS0000: message`. */
const buildErrors = output => [...output.matchAll(/^\s*(.+?)\((\d+),(\d+)\): error (CS\d+): (.+?)(?: \[.*\])?$/gm)].map(match => ({ file: match[1], line: Number(match[2]), column: Number(match[3]), code: match[4], message: match[5] }));

/**
 * The copy made ready: every mutant written into its file, a switch in each project that has any, and the solution built, again
 * without whatever the compiler rejects, until it builds.
 */
export async function prepare({ copies: [copy], generated, graph }) {
  ids = new Map(); keys = new Map(); unplaced = new Map(); assemblies = []; names = new Map(); testOfNode = new Map();
  const env = { ...process.env, DOTNET_CLI_TELEMETRY_OPTOUT: '1', DOTNET_NOLOGO: '1' };
  for (const node of graph.nodes.values()) if (node.case && languages.has(graph.files.get(node.path)?.file.language)) names.set(node.qualified_name, node.id);
  const all = await projects(copy.dir);
  const isTest = async project => /Microsoft\.NET\.Test\.Sdk|<IsTestProject>\s*true/i.test(await readFile(project, 'utf8'));
  const tests = [];
  for (const project of all) if (await isTest(project)) tests.push(project);
  if (!tests.length) throw new Error('there is no test project: none references Microsoft.NET.Test.Sdk');
  const byFile = new Map();
  let next = 0;
  for (const [methodId, mutants] of generated) {
    const node = graph.nodes.get(methodId);
    if (!byFile.has(node.path)) byFile.set(node.path, []);
    for (const mutant of mutants) {
      const key = `${methodId}#${mutantId(mutant)}`, id = next++;
      ids.set(key, id);
      keys.set(id, { key, mutant, path: node.path });
      byFile.get(node.path).push({ id, mutant });
    }
  }
  // The project a file is in: the one whose directory holds it most closely.
  const owners = new Set([...byFile.keys()].map(path => all.filter(project => join(copy.dir, path).startsWith(`${dirname(project)}/`)).sort((a, b) => b.length - a.length)[0]).filter(Boolean));
  for (const project of owners) await writeFile(join(dirname(project), 'PerchSwitch.g.cs'), SWITCH);
  const sources = new Map();
  for (const path of byFile.keys()) sources.set(path, await readFile(join(copy.dir, path), 'utf8'));
  for (let round = 0; ; round++) {
    const placed = new Map();
    for (const [path, mutants] of byFile) {
      const result = instrument({ source: sources.get(path), language: 'csharp', mutants: mutants.filter(item => !unplaced.has(item.id)) });
      for (const { id, reason } of result.unplaced) unplaced.set(id, reason);
      placed.set(path, result);
      await writeFile(join(copy.dir, path), result.text);
    }
    // Each test project, which builds every project it references.
    let output = '', failed = false;
    for (const project of tests) {
      try {
        ({ stdout: output } = await run('dotnet', ['build', project, '-nologo', '-clp:NoSummary', '-p:TreatWarningsAsErrors=false', '-p:WarningLevel=0'], { cwd: copy.dir, env, maxBuffer: 1 << 28 }));
      } catch (error) { output = `${error.stdout ?? ''}${error.stderr ?? ''}`; failed = true; break; }
    }
    const errors = buildErrors(output);
    if (!errors.length && failed) throw new Error(`dotnet could not build the tests: ${output.trim().split('\n').slice(-4).join(' | ')}`);
    if (!errors.length) break;
    const rejected = new Set();
    for (const error of errors) {
      const path = relative(copy.dir, error.file.startsWith('/') ? error.file : join(copy.dir, error.file));
      for (const id of placed.get(path)?.locate(error.line, error.column) ?? []) rejected.add(id);
    }
    if (!rejected.size || round > 20) throw new Error(`the solution does not build: ${errors.slice(0, 3).map(error => `${error.file}(${error.line}): ${error.code} ${error.message}`).join(' | ')}`);
    for (const id of rejected) unplaced.set(id, `the compiler rejects it: ${errors.find(error => placed.get(relative(copy.dir, error.file.startsWith('/') ? error.file : join(copy.dir, error.file))))?.message ?? 'error'}`);
  }
  // The built test assemblies: each test project's own dll, by the name of its project.
  for (const project of tests) {
    const text = await readFile(project, 'utf8');
    const assembly = /<AssemblyName>([^<]+)</.exec(text)?.[1] ?? project.split('/').at(-1).replace(/\.csproj$/, '');
    const { stdout } = await run('find', [join(dirname(project), 'bin'), '-name', `${assembly}.dll`, '-path', '*/bin/*'], { maxBuffer: 1 << 20 });
    const found = stdout.split('\n').filter(path => path && !path.includes('/ref/'));
    if (found.length) assemblies.push(found.sort().at(-1));
  }
  if (!assemblies.length) throw new Error('dotnet built no test assembly');
}

/** `dotnet test` over the built assemblies, into a results directory of its own: each test case's result. */
async function testRun(driver, { cwd, results, env, filter, timeout }) {
  await rm(results, { recursive: true, force: true });
  const ran = await driver.exec('dotnet', ['test', ...assemblies, '--results-directory', results, '--logger', 'trx', ...(filter ? ['--filter', filter] : [])],
    { cwd, env: { DOTNET_CLI_TELEMETRY_OPTOUT: '1', DOTNET_NOLOGO: '1', ...env }, timeout });
  const found = [];
  for (const file of await readdir(results).catch(() => [])) if (file.endsWith('.trx')) found.push(...readTrx(await readFile(join(results, file), 'utf8')));
  return { ran, found };
}

/** The suite once, every switch recording which test reached it. */
export async function coverageRun({ copy, scratch }) {
  const hits = join(scratch, 'hits.tsv');
  await writeFile(hits, '');
  const started = Date.now();
  const driver = await startDriver({ scratch, writable: [copy, scratch] });
  let outcome;
  try { outcome = await testRun(driver, { cwd: copy, results: join(scratch, 'coverage-results'), env: { PERCH_COVERAGE: '1', PERCH_HITS: hits } }); } finally { await driver.close(); }
  if (!outcome.found.length) throw new Error(`dotnet test ran no tests (exit ${outcome.ran.code}): ${outcome.ran.output.trim().split('\n').slice(-5).join(' | ')}`);
  const results = new Map();
  for (const item of outcome.found) {
    const test = testIdOf(item.name);
    const had = results.get(item.name);
    results.set(item.name, { test, status: had?.status === 'failed' ? 'failed' : item.status, time: item.time });
    testOfNode.set(item.name, test);
  }
  const reached = new Map(), executed = new Map();
  for (const line of (await readFile(hits, 'utf8')).split('\n').filter(Boolean)) {
    const [id, method] = line.split('\t');
    if (!method) continue;
    const test = testIdOf(method);
    if (!reached.has(test)) { reached.set(test, new Set()); executed.set(test, new Map()); }
    const { key, mutant, path } = keys.get(Number(id));
    reached.get(test).add(key);
    const lines = executed.get(test);
    if (!lines.has(path)) lines.set(path, new Set());
    for (const item of mutant.statements.length ? mutant.statements : [mutant.line]) lines.get(path).add(item);
  }
  const hitMethods = new Set([...keys.values()].map(({ key }) => key.slice(0, key.lastIndexOf('#'))));
  return { executed, hits: reached, hitMethods, unplaced: new Set([...unplaced.keys()].map(id => keys.get(id).key)), results, seconds: (Date.now() - started) / 1000 };
}

/** Each mutant run by `dotnet test` over the built assemblies, with its number set and only the methods of its tests named. */
export async function session({ copies: [copy] }) {
  const driver = await startDriver({ scratch: copy.scratch, writable: [copy.dir, copy.scratch] });
  let count = 0;
  return {
    async run({ mutant, method, nodes, timeout }) {
      const id = ids.get(`${method.id}#${mutantId(mutant)}`);
      if (unplaced.has(id)) return { status: 'invalid', error: unplaced.get(id) };
      const filter = [...new Set(nodes.map(methodOf))].map(name => `FullyQualifiedName=${name.replace(/([\\(),&|=!~])/g, '\\$1')}`).join('|');
      const results = join(copy.scratch, `results-${count++}`);
      const { ran, found } = await testRun(driver, { cwd: copy.dir, results, env: { PERCH_MUTANT: String(id) }, filter, timeout });
      await rm(results, { recursive: true, force: true });
      if (ran.timedOut) return { status: 'timeout' };
      const outcome = new Map(found.map(item => [item.name, item.status]));
      if (!nodes.some(node => outcome.has(node))) {
        // The host crashed before it reported: every test it was running failed, which the mutant made happen.
        if (ran.code !== 0 && !found.length) return { status: 'ran', results: new Map(nodes.map(node => [node, { test: testOfNode.get(node), status: 'failed' }])) };
        return { status: 'invalid', error: ran.output.trim().split('\n').slice(-3).join(' | ') };
      }
      return { status: 'ran', results: new Map(nodes.filter(node => outcome.has(node)).map(node => [node, { test: testOfNode.get(node), status: outcome.get(node) }])) };
    },
    close: () => driver.close(),
  };
}
